### ISSUE TITLE
Question an about ''django dropbox'' static upload error occur “ cStringIO ”

### ISSUE THREAD

**Issue by Ravindrakumara** [zuck/django-dropbox-storage#7]
model.py
----------
from cStringIO import StringIO
from django.db import models
from django_dropbox_storage.storage import DropboxStorage

store = DropboxStorage()

class Brands(models.Model):
    Brand_Name = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='photos', storage=store)

Error traceback
----------------
C:\Users\user\Documents\django\go\go\db\models.py changed, reloading.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "c:\users\user\appdata\local\programs\python\python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Documents\django\go\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\user\Documents\django\go\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\user\Documents\django\go\lib\site-packages\django\utils\autoreload.py", line 76, in raise_last_exception
    raise _exception[1]
  File "C:\Users\user\Documents\django\go\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\user\Documents\django\go\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\user\Documents\django\go\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\user\Documents\django\go\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\user\Documents\django\go\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "c:\users\user\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\user\Documents\django\go\go\db\models.py", line 4, in <module>
    from cStringIO import StringIO
ModuleNotFoundError: No module named 'cStringIO'

**Comment by loictessier** [comment]
I've had the same problem with cStringIO which became io, it's been fixed with the last commit https://github.com/zuck/django-dropbox-storage/commit/4db1884e86ff754697b68e7c02745ac838b99f90 but it has not been published under a new version yet, but you can install directly from the git repo with pip to get the fix on your project.
`python -m pip install git+https://github.com/zuck/django-dropbox-storage.git#egg=django-dropbox-storage `

**Comment by av1m** [comment]
Hi,
Duplicate #3
You can close this issue.

We are still waiting for their release
